#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII 

bspc config border_width         2
bspc config window_gap           5 
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding 	 20 

bspc config focused_border_color "#4e5460"
bspc config normal_border_color "#2e3440"

xsetroot -cursor_name left_ptr &
xbacklight -set 30
xinput set-prop 12 309 1